//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLTV2MXF_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string HelloWorld {
            get {
                return ((string)(this["HelloWorld"]));
            }
            set {
                this["HelloWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usePreProcessor {
            get {
                return ((bool)(this["usePreProcessor"]));
            }
            set {
                this["usePreProcessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XMLTVNZ")]
        public string ProviderString {
            get {
                return ((string)(this["ProviderString"]));
            }
            set {
                this["ProviderString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usePostProcessor {
            get {
                return ((bool)(this["usePostProcessor"]));
            }
            set {
                this["usePostProcessor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\windows\\ehome\\LoadMXF.exe -i $OUTPUTFILE")]
        public string postProcessorCommand {
            get {
                return ((string)(this["postProcessorCommand"]));
            }
            set {
                this["postProcessorCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Guide\\xmlTVNZ.exe $INPUTFILE -days 7 -nooffset default_tv1 default_tv2 default" +
            "_tv3 default_c4 default_tvnz6 default_tvnz7 default_tvnzsportextra default_maori" +
            "")]
        public string preProcessorCommand {
            get {
                return ((string)(this["preProcessorCommand"]));
            }
            set {
                this["preProcessorCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Guide\\xmltvnz.xml")]
        public string inputXMLTVfile {
            get {
                return ((string)(this["inputXMLTVfile"]));
            }
            set {
                this["inputXMLTVfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Guide\\Guide.MXF")]
        public string outputMXFfile {
            get {
                return ((string)(this["outputMXFfile"]));
            }
            set {
                this["outputMXFfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Channels.xml")]
        public string ChannelsXML {
            get {
                return ((string)(this["ChannelsXML"]));
            }
            set {
                this["ChannelsXML"] = value;
            }
        }
    }
}
